
---
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    username: root
    password: 721000
    url: jdbc:mysql://localhost:3306/ssm_crud?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
---
mybatis:
  config-location: classpath:public/MapperConfig.xml
  mapper-locations:
    - classpath:public/Mapper/DepartmentMapper.xml
    - classpath:public/Mapper/EmployeeMapper.xml
---
spring:
  thymeleaf:
    cache: false